'use strict';
const $=id=>document.getElementById(id),stages=['Headliner','Headliner','Main stage','Main stage','Discovery','Discovery'];let artists=[],state,pageData,posterBill;const DEFAULT_WEIGHTS=[50,30,20];
function weights(){return state?.config?.weights||DEFAULT_WEIGHTS}

function el(tag,cls,text){const e=document.createElement(tag);e.className=cls;if(text!=null)e.textContent=text;return e}
function compact(n){return n==null?'Unavailable':Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n)}
function commercial(n,max){return Math.min(99,Math.max(0,99*Math.log10(1+n/1e6)/Math.log10(1+max/1e6)))}
function rate(a){const [wt,wr,ws]=weights();let total=a.talent*wt,weight=wt;if(a.records!=null){total+=commercial(a.records,400e6)*wr;weight+=wr}if(a.streams!=null){total+=commercial(a.streams,130e9)*ws;weight+=ws}return weight?Math.round(total/weight):a.talent}
function gameTrait(a,kind){return Math.min(99,Math.max(50,Math.round(a.talent+(kind==='creativity'?(a.scene==='Discovery'?4:0):(a.scene==='Legend'?3:1)))))}
function random(){if(!state?.daily)return Math.random();state.rng=(Math.imul(state.rng,1664525)+1013904223)>>>0;return state.rng/4294967296}
function hash(s){let n=2166136261;for(const c of s)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0}
function save(){try{localStorage.setItem('encore-v1',JSON.stringify(state))}catch{}}
function turn(){return state.mode==='solo'?0:(Math.floor(state.turn/2)%2===0?state.turn%2:1-state.turn%2)}
function pool(stage,config){return artists.filter(a=>stage==='Discovery'?a.scene==='Discovery':a.scene!=='Discovery'&&(config.genre==='all'||a.genre===config.genre)&&(config.scene==='all'||a.scene===config.scene))}
function offer(){const t=state.teams[turn()],stage=stages[t.roster.length],used=new Set(state.teams.flatMap(t=>t.roster.map(a=>a.id)));let available=pool(stage,state.config).filter(a=>!used.has(a.id));const prev=new Set(state.offers.map(a=>a.id)),fresh=available.filter(a=>!prev.has(a.id));if(fresh.length>=3)available=fresh;state.offers=[];while(state.offers.length<3&&available.length){const i=Math.floor(random()*available.length);state.offers.push(available.splice(i,1)[0])}save();render()}
function start(daily=false){daily=daily===true;const chosenWeights=daily?DEFAULT_WEIGHTS:['wt','wr','ws'].map(id=>Math.max(0,Math.min(100,Number($(id).value)||0)));if(!chosenWeights.some(w=>w>0)){$('error').textContent='Give at least one rating category a weight.';$('error').hidden=false;return}const config={weights:chosenWeights,genre:$('genre').value,scene:$('scene').value};if(daily){config.genre='all';config.scene='all'}const needed=daily||$('mode').value==='solo'?4:8;if(pool('Headliner',config).length<needed){$('error').textContent='That mix needs more artists. Try Mixed genres or Legends + current.';$('error').hidden=false;return}$('error').hidden=true;state={daily:daily?day():null,rng:hash(day()),mode:daily?'solo':$('mode').value,config,turn:0,stage:'draft',offers:[],teams:[{name:$('name').value.trim()||'After Hours Fest',roster:[],rerolls:2},{name:'Your friend’s festival',roster:[],rerolls:2}],scores:[]};track('starts');offer()}
function pick(id){if(state.stage!=='draft')return;const a=state.offers.find(a=>a.id===id);if(!a)return;state.teams[turn()].roster.push(a);state.turn++;if(state.turn===(state.mode==='solo'?6:12)){state.stage='ready';save();render()}else offer()}
function card(a){const b=el('button','player'+(a.scene==='Discovery'?' discovery':''));b.type='button';b.setAttribute('aria-label','Draft '+a.name+', overall '+rate(a));const top=el('span','player-top');top.append(el('span','team-mark',a.scene==='Discovery'?'NEXT UP':a.scene.toUpperCase()),el('span','season',a.genre));const body=el('span','player-body');body.append(el('strong','player-name',a.name));const meta=el('span','player-meta');meta.append(el('span','position',a.genre));const rating=el('span','rating',rate(a));rating.append(el('small','','OVR'));meta.append(rating);body.append(meta);const grid=el('span','stat-grid');for(const [label,value] of [['Talent (editorial)',a.talent+'/99'],a.streams!=null?['Spotify streams',compact(a.streams)]:['Creativity (game)',gameTrait(a,'creativity')+'/99'],['Stage appeal (game)',gameTrait(a,'stage')+'/99']]){const item=el('span','');item.append(el('b','',value),el('small','',label));grid.append(item)}body.append(grid,el('span','rating-note',a.streams==null&&a.records==null?'Provisional overall · talent only':'Commercial snapshot + editorial talent'));b.append(top,body,el('span','draft-cta','Book '+a.name+' →'));b.onclick=()=>pick(a.id);return b}
function lineupScore(t){const average=t.roster.reduce((sum,a)=>sum+rate(a),0)/t.roster.length;const genres=new Set(t.roster.map(a=>a.genre)).size;return Math.min(99,Math.round(average+Math.min(4,genres-1)))}
function render(){const t=state.teams[turn()];$('welcome').hidden=true;$('archive').hidden=true;$('game').hidden=false;$('headline').textContent=t.name;$('phase').textContent=state.daily?'DAILY CHALLENGE · '+state.daily:state.mode==='versus'?'PASS THE DEVICE · '+t.name.toUpperCase():'YOUR FESTIVAL';$('overall').textContent=t.roster.length?lineupScore(t)+' OVR':'—';$('roster').replaceChildren();stages.forEach((stage,i)=>{const row=el('div','slot'),a=t.roster[i];row.append(el('b','',stage==='Discovery'?'NEW':stage==='Headliner'?'HEAD':'MAIN'),el('span','',a?a.name:'Open slot'),el('em','',a?rate(a):'—'));$('roster').append(row)});$('chemistry').textContent='A mix of genres earns up to +4 lineup points.';const draft=state.stage==='draft';$('draft').hidden=!draft;$('results').hidden=draft;if(!draft){results();return}const stage=stages[t.roster.length];$('picklabel').textContent=stage==='Discovery'?'Find your next-up act':'Book a '+stage.toLowerCase();$('counter').textContent='Pick '+(t.roster.length+1)+' of 6';$('progress').style.width=t.roster.length/6*100+'%';$('hint').textContent=stage==='Discovery'?'Give an emerging or cult-favorite act a spot. Discovery artists always get two slots.':'Compare talent, catalog performance, and streaming reach. Every artist brings a different crowd.';$('choices').replaceChildren();state.offers.forEach(a=>$('choices').append(card(a)));$('reroll').textContent='↻ Reroll choices ('+t.rerolls+' left)';$('reroll').disabled=t.rerolls===0}
function run(){if(state.daily)state.rng=hash(state.daily+state.teams[0].roster.map(a=>a.id).join(','));if(state.stage!=='ready')return;state.scores=state.teams.slice(0,state.mode==='solo'?1:2).map(t=>{const base=lineupScore(t),review=Math.min(99,Math.max(40,Math.round(base+(random()-.5)*8))),buzz=Math.min(99,Math.round(base*.7+t.roster.filter(a=>a.scene==='Discovery').reduce((s,a)=>s+a.talent,0)*.15+(random()-.5)*8));return {review,buzz,crowd:Math.round(3000+base*1100+random()*12000),score:Math.round(review*.65+buzz*.35)}});state.stage='done';track('completed');remember();save();render()}
function action(label,fn,primary=true){const b=el('button',primary?'primary':'',label);b.onclick=fn;return b}
function results(){const out=$('results');out.replaceChildren();if(state.stage==='ready'){state.teams.slice(0,state.mode==='solo'?1:2).forEach(t=>out.append(budgetCard(t)));out.append(el('h2','','The bill is booked.'),el('p','','Six acts. Two stages. Let’s see how the weekend goes.'),action('Open the gates →',run));return}state.scores.forEach((s,i)=>{out.append(el('div','eyebrow',state.teams[i].name),el('div','score',s.score+'/100'));const m=el('div','result-metrics');for(const [label,value] of [['Simulated crowd',compact(s.crowd)],['Review score',s.review+'/100'],['Discovery buzz',s.buzz+'/100']]){const item=el('div','');item.append(el('b','',value),el('small','',label));m.append(item)}out.append(m,budgetCard(state.teams[i]))});if(state.mode==='versus'){const [a,b]=state.scores;out.append(el('h2','',a.score===b.score?'A festival tie. Both bills delivered.':state.teams[a.score>b.score?0:1].name+' wins!'),action('View other lineup',()=>{state.turn=turn()===0?1:0;save();render()},false))}else out.append(el('h2','',state.scores[0].score>=90?'A weekend people will talk about.':'A solid bill. Who would you book next?'));out.append(action('Make a shareable poster',()=>showPoster(bill(turn()))),action('Build another festival',reset))}
function reset(){$('game').hidden=true;$('welcome').hidden=false;state=null;try{localStorage.removeItem('encore-v1')}catch{}}
function browse(){const q=$('search').value.trim().toLowerCase();$('archive-rows').replaceChildren();artists.filter(a=>a.name.toLowerCase().includes(q)).forEach(a=>{const row=el('div','archive-row');const info=el('div','');info.append(el('strong','',a.name),el('p','',a.genre+' · '+a.scene+' · '+rate(a)+' OVR'));const data=el('div','');data.append(el('p','','Talent (editorial): '+a.talent+'/99\nSpotify lead streams: '+compact(a.streams)+'\nNon-stream record units: '+compact(a.records)));data.style.whiteSpace='pre-line';if(a.source){const link=el('a','','View source ↗');link.href=a.source;link.target='_blank';link.rel='noopener';data.append(link)}if(a.recordSource){const link=el('a','',' · Record source ↗');link.href=a.recordSource;link.target='_blank';link.rel='noopener';data.append(link)}row.append(info,data);$('archive-rows').append(row)})}
$('start').onclick=()=>start();$('reset').onclick=reset;$('reroll').onclick=()=>{if(state.stage==='draft'&&state.teams[turn()].rerolls){state.teams[turn()].rerolls--;offer()}};$('browse-toggle').onclick=()=>{$('archive').hidden=false;browse()};$('close').onclick=()=>{$('archive').hidden=true};$('search').oninput=browse;
async function load(){try{const response=await fetch('artists.json');if(!response.ok)throw Error('Artist data unavailable');pageData=await response.json();artists=pageData.artists;$('status').textContent=artists.length+' artists in the crate · Commercial data is a dated snapshot; talent scores are editorial.';$('start').disabled=false;$('daily').disabled=false;$('start').textContent='Start booking →';try{const s=JSON.parse(localStorage.getItem('encore-v1'));if(s&&s.teams?.length===2&&['draft','ready','done'].includes(s.stage)){state=s;render()}}catch{}}catch(e){$('status').textContent='Couldn’t load the artist crate. Reload to try again.'}}
load().then(()=>{track('visit');const incoming=new URLSearchParams(location.hash.slice(1)).get('bill');if(incoming&&incoming.length<4000){try{const b=JSON.parse(incoming);if(Array.isArray(b.ids)&&b.ids.length===6&&new Set(b.ids).size===6&&b.ids.every(id=>artists.some(a=>a.id===id))&&typeof b.name==='string'&&b.name.length<=30&&Number.isFinite(b.score)&&b.score>=0&&b.score<=100)showPoster(b)}catch{}}});
function day(){return new Date().toISOString().slice(0,10)}
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function track(event){const t=read('encore-test-stats',{days:[],starts:0,completed:0});if(event==='visit'&&!t.days.includes(day()))t.days.push(day());if(event==='starts')t.starts++;if(event==='completed')t.completed++;write('encore-test-stats',t)}
function bill(i){return {name:state.teams[i].name,ids:state.teams[i].roster.map(a=>a.id),score:state.scores[i]?.score??lineupScore(state.teams[i]),daily:state.daily||null,theme:$('theme').value||'classic'}}
function remember(){let list=read('encore-lineups',[]);state.teams.slice(0,state.mode==='solo'?1:2).forEach((_,i)=>list.unshift({...bill(i),saved:new Date().toISOString()}));write('encore-lineups',list.slice(0,20))}
function money(n){return Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)}
function budget(roster){const booking=roster.reduce((sum,a)=>sum+(a.scene==='Discovery'?15000+gameTrait(a,'stage')*700:100000+Math.pow(rate(a)/99,4)*1900000),0);const production=300000+booking*.35,total=booking+production;return {booking:Math.round(booking),production:Math.round(production),low:Math.round(total*.7),high:Math.round(total*1.3)}}
function budgetCard(t){const b=budget(t.roster),wrap=el('div','budget');wrap.append(el('h3','','Estimated festival budget'),el('strong','budget-total',money(b.low)+' – '+money(b.high)),el('p','','Fantasy planning range · USD · one-day, two-stage event'),el('p','','Artist bookings: about '+money(b.booking)+'\nProduction, staff & venue: about '+money(b.production)),el('small','','These are game-model estimates, not researched booking fees or quotes. Actual costs depend on venue, capacity, dates, contracts and artist availability.'));return wrap}
const palettes={classic:['#e8ba58','#2e2238','#774297'],sunset:['#e98968','#392322','#fff1c8'],midnight:['#222337','#f3efda','#ab99df']};
function showPoster(b){posterBill={...b};$('poster-panel').hidden=false;const canvas=$('poster'),ctx=canvas.getContext('2d'),[bg,fg,accent]=palettes[b.theme]||palettes.classic;ctx.fillStyle=bg;ctx.fillRect(0,0,1080,1350);ctx.fillStyle=fg;ctx.textAlign='center';ctx.font='700 34px system-ui';ctx.fillText('ENCORE / YOUR DREAM FESTIVAL',540,90);ctx.font='900 88px system-ui';ctx.fillText('THE LINEUP',540,210);ctx.font='500 35px system-ui';ctx.fillText(b.name,540,280,920);const acts=b.ids.map(id=>artists.find(a=>a.id===id)).filter(Boolean);acts.forEach((a,i)=>{ctx.font='700 '+(i<2?62:48)+'px system-ui';ctx.fillText(a.name,540,420+i*110,920);ctx.font='500 24px system-ui';ctx.fillText(stages[i].toUpperCase()+' / '+a.genre,540,459+i*110,920)});ctx.fillStyle=accent;ctx.fillRect(75,1120,930,3);ctx.fillStyle=fg;ctx.font='700 45px system-ui';ctx.fillText('FESTIVAL SCORE '+b.score+'/100',540,1210);ctx.font='500 25px system-ui';ctx.fillText('FANTASY LINEUP · '+(b.daily?'DAILY '+b.daily:'PLAY ENCORE'),540,1280);$('share-status').textContent='Download your poster or send the lineup link.'}
function shareLink(){const u=new URL(location.href);u.hash=new URLSearchParams({bill:JSON.stringify(posterBill)}).toString();return u.href}
$('poster-close').onclick=()=>{$('poster-panel').hidden=true};$('download').onclick=()=>{$('poster').toBlob(blob=>{if(!blob){$('share-status').textContent='Could not create the poster. Try again.';return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='encore-festival-poster.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(shareLink());$('share-status').textContent='Lineup link copied.'}catch{$('share-status').textContent='Copy this link: '+shareLink()}};
$('share').onclick=async()=>{try{if(navigator.share){await navigator.share({title:posterBill.name,text:'Would you attend my festival? '+posterBill.score+'/100 on Encore.',url:shareLink()});$('share-status').textContent='Shared.'}else await $('copy').onclick()}catch(e){$('share-status').textContent=e.name==='AbortError'?'Sharing canceled.':'Use Download poster or Copy lineup link.'}};
$('daily').onclick=()=>start(true);$('daily-info').textContent='Daily challenge: '+day()+' · Same choices for everyone · resets at midnight UTC.';
$('theme').onchange=()=>{write('encore-theme',$('theme').value);if(posterBill){posterBill.theme=$('theme').value;showPoster(posterBill)}};$('theme').value=read('encore-theme','classic');
$('saved-toggle').onclick=()=>{$('saved-panel').hidden=!$('saved-panel').hidden;const list=read('encore-lineups',[]);$('saved-list').replaceChildren();if(!list.length)$('saved-list').append(el('p','','Finish a festival to save its lineup here.'));list.forEach(b=>$('saved-list').append(action(b.name+' · '+b.score+'/100',()=>showPoster(b),false)))};
$('stats-toggle').onclick=()=>{$('stats-panel').hidden=!$('stats-panel').hidden;const t=read('encore-test-stats',{days:[],starts:0,completed:0});$('stats-text').textContent='Visit days: '+t.days.length+' · Return days: '+Math.max(0,t.days.length-1)+' · Drafts started: '+t.starts+' · Festivals completed: '+t.completed+' · Completion: '+(t.starts?Math.round(t.completed/t.starts*100):0)+'%. This counts this browser only, not all visitors.'};
